FROM grafana/grafana:latest
USER root

RUN apk update
RUN apk add --no-cache openssl
RUN apk add --no-cache bash
COPY setup.sh /tmp/
COPY grafana.ini /tmp/ 
RUN chmod +x /tmp/setup.sh
EXPOSE 3000

ENTRYPOINT ["/bin/sh", "/tmp/setup.sh"]